services:
  nginx:
    build: ./build/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/seccon/_.seccon.games.crt:/etc/nginx/certs/server.crt:ro
      - /etc/seccon/_.seccon.games.key:/etc/nginx/certs/server.key:ro
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - app
    environment:
      TZ: "Asia/Tokyo"
  app:
    build:
      context: ./files/app
